name: CI

# 1
on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      version:
        description: 'Image version'
        required: true

#2
env:
  REGISTRY: "registry.digitalocean.com/fanzty-registry"
  IMAGE_NAME: "fanzty-registry"

#3
jobs:
  test_ssh_connection:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into Droplet and Execute Commands
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSHKEY }}
          script: |
            echo "SSH Connection Successful!" 
            whoami  # Display the current user
            pwd    # Display the current working directory
